[package]
name = "fpdb-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.10"
diesel = { version = "2.1.0", features = ["sqlite", "chrono"] }
libsqlite3-sys = { version = "0.26.0", features = ["bundled"] }
dotenv = "0.15.0"
chrono = "0.4"
regex = "1.5"
